# Reference: https://jenkinsci.github.io/kubernetes-operator/docs/installation/
apiVersion: jenkins.io/v1alpha2
kind: Jenkins
metadata:
  name: persistent
  labels:
    app: jenkins-persistent
  namespace: rh-dev
spec:
  persistentSpec:
    enabled: true
    # Use OCS block storage (Ceph RADOS Block Device volumes)
    #storageClassName: ocs-storagecluster-ceph-rbd
    # Use AWS-ebs volume
    storageClassName: gp2
    volumeSize: 5Gi
  metricsEnabled: true
  backupEnabled: false
